### ISSUE TITLE
Fixes to use this example on an Ubuntu DL AMI (Version 13)

### ISSUE THREAD

**Issue by markmp** [aws-samples/deep-learning-models#1]
Hi - I spent some time getting this Tensorflow example (train_resnet50_imagenet.sh) running in the current deep-learning AMI (version 13, ubuntu/conda) using p3.16xlarge instances. There were quite a few changes needed to get this to actually run (and even more for multi-node). I did not use the CloudFormation script.

1) Modify default .bashrc to move the PATH stuff to the top of the file, above the interactive shell check. Otherwise, remote ssh commands would not be able to activate the conda environment
2) write a small bash wrapper script to call "source activate tensorflow_p36" to activate the environment before calling the training script with python. I pass this wrapper script to MPI. This is my full MPI command:
mpirun -np 64 --hostfile hosts -mca plm_rsh_no_tree_spawn 1 --bind-to socket --map-by slot -x NCCL_DEBUG=INFO -x NCCL_MIN_NRINGS=4 -x LD_LIBRARY_PATH -x PATH -x NCCL_SOCKET_IFNAME=ens3 -mca orte_base_help_aggregate 0 -mca pml ob1 -mca btl_tcp_if_exclude lo,docker0 -mca btl ^openib /home/ubuntu/examples/horovod/cnn/wrapenv.sh python aws_tf_hvd_cnn.py --batch_size=256 --num_epochs=90 --fp16 --data_dir /home/ubuntu/imagenet/train-resized --model resnet50 --log_dir results --display_every 100 --save_interval=3600

3) Add the magic parameters "-x NCCL_SOCKET_IFNAME=ens3" and  "-mca btl_tcp_if_exclude lo,docker0" (ens3 was the interface if I ran 'ifconfig').  Without these parameters, the mpirun command would fail. Specifically, it would hang with this error: 
[btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[45621,1],10] 

Digging around the Horovod Git - it seems this might be related to Docker/Virtualization. I wasn't using anything beyond just running the DLAMI Ubuntu/Conda V13 in EC2. When I added these parameters, everything starting working. 

4) Copy all the validation example shards into the same data directory as the training data. Unlike the Horovod example that's baked into the DL AMI - all data (training + val) needs to be in same place, even when just doing "--eval". 

To go multi-node, I needed to do these additional steps:
1) make sure remote SSH commands work node-to-node (e.g. authorized keys + known_hosts setup right)
2) Put instances in placement group
3) Add IAM role so each instance can access buckets, etc.
4) Set security group to allow TCP traffic on any port from machines only in security group
5) Set /etc/hosts and MPI hostfile appropriately  (and put in VPC so internal IPs don't change).

Hopefully this can help others spin up their own parallel cluster.

**Comment by rahul003** [comment]
Thanks for sharing your findings here. We've improved the readme, added a working bash script for DLAMI, fixed the non interactive shell check in .bashrc and updated this to be the example in the latest version of DLAMI.

**Comment by rahul003** [comment]
The updated scripts are now available both here and in the latest DLAMI under `examples/horovod/tensorflow`
