### ISSUE TITLE
ALBERT blog - where is the cloudformation template?

### ISSUE THREAD

**Issue by jiyang-kang** [aws-samples/deep-learning-models#18]
Hi, 
this is about the AWS blog article, "Train ALBERT for natural language processing with TensorFlow on Amazon SageMaker":
[https://aws.amazon.com/blogs/machine-learning/train-albert-for-natural-language-processing-with-tensorflow-on-amazon-sagemaker/
](https://aws.amazon.com/blogs/machine-learning/train-albert-for-natural-language-processing-with-tensorflow-on-amazon-sagemaker/
)
where can I find the cloudformation template (`fsx.yaml`) to create an FSx volume?

**Comment by jarednielsen** [comment]
One level up: https://github.com/aws-samples/deep-learning-models/tree/master/models/nlp/cloudformation

**Comment by jiyang-kang** [comment]
Thanks for quick response. It's not clear in the blog article.

**Comment by jiyang-kang** [comment]
I find the cloudformation CLI command in the blog article should be modified.
This is not working (current): `aws cloudformation create-stack --template-body cloudformation/fsx.yaml --stack-name fsx-albert`
with errors: 
`An error occurred (ValidationError) when calling the CreateStack operation: Template format error: unsupported structure.`

This is working: `aws cloudformation create-stack --template-body file://cloudformation/fsx.yaml --stack-name fsx-albert`

ref: [https://stackoverflow.com/questions/41992569/template-format-error-unsupported-structure-seen-in-aws-cloudformation](https://stackoverflow.com/questions/41992569/template-format-error-unsupported-structure-seen-in-aws-cloudformation)

**Comment by jarednielsen** [comment]
Thank you for the feedback, I've updated the blog post with the proper parameter and a clearer file location.
