### ISSUE TITLE
BERT Pre-Training crashes with TF 2.4 

### ISSUE THREAD

**Issue by piyushghai** [aws-samples/deep-learning-models#44]
Here's the error when trying to run BERT pre-training with TF 2.4. 
The same error is also seen for ALBert pre-training. 

```[1,6]<stdout>:  File "albert/run_pretraining.py", line 672, in <module>
[1,6]<stdout>:    main()
[1,6]<stdout>:  File "albert/run_pretraining.py", line 513, in main
[1,6]<stdout>:    loss_scale = optimizer.loss_scale()
[1,6]<stdout>:TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable
```

**Comment by satishpasumarthi** [comment]
Hi @piyushghai
LossScaleOptimizer.loss_scale is now a tensor, not a LossScale object.  You need to change the line https://github.com/aws-samples/deep-learning-models/blob/master/models/nlp/albert/run_pretraining.py#L509 to optimizer.loss_scale. For more information, please refer
https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0
