### ISSUE TITLE
Increasing the number of tfrecord data blocks leads to test accuracy loss

### ISSUE THREAD

**Issue by Tron-x** [aws-samples/deep-learning-models#9]
Hi, I am running a distributed training experiment, training Imagenet to use resnet50. When I shard Imagenet into 1024 tfrecord, the experiment is correct, whether I use 1024gpu or 2048gpus. But when I shard Imagenet into 2048 tfreocrd. No matter how many cards I use(8gpus, 1024gpus，2048gpus), the test accuracy will be lost. But I didn't find out what was wrong with reading the data on this script.I can't find the problem. can you help me, thank you very much!

**Comment by rahul003** [comment]
That sounds strange. Can you check if you're somehow not reading some of your shards?

**Comment by Tron-x** [comment]
It's really strange ，1024 GPUs using 1024 blocks and 2048gpu using 2028 blocks should be the same. I haven't found any problems from that code make_dataset, but 2048 blocks of data cause a lot of loss of test accuracy (2048gpus final test accuracy is 10%) (8gpus final test accuracy is 40%),Can you check it for me? This problem has been bothering me for a long time，thanks!,I also sent you an email。

**Comment by Tron-x** [comment]
Hi, this problem has been bothering me for a while. Can you check it for me, thank you.
